name: WJK4_design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6896282169036567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#c69c6d'
    - '#000000'
    - '#f15a24'
    - '#987753'
  brandStrength: 0.75
  lightness: 0.8406081139110029
  saturation: 0.3125
  rhythmicContrast: 0.48367991228587925
purpose: []
