name: WJK4_design
favicon: null
layout_spectrum: 0.7023030128329992
typography_spectrum: 0.6896282169036567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0593384534586221
  lightness: 0.8406081139110029
  saturation: 0.1549321156926453
  rhythmicContrast: 0.48367991228587925
purpose: []
